FROM oven/bun:1-alpine

WORKDIR /usr/src/app

ARG DATABASE_URL

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock
COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json
COPY ./apps/web ./apps/web

RUN bun install
RUN bun run db:generate
ENV DATABASE_URL=${DATABASE_URL} 
RUN echo "${DATABASE_URL}"
RUN bun run build:web

EXPOSE 3000

CMD ["bun", "run", "start:web"]